config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  get 'contact_us' => 'home#contact_us'

  get 'menu' => 'home#menu'

  root 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end



  def contact_us
  end

  def menu
  	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact_us.html.erb
<h1>This is all about us</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h3>
      	Address
      </h3>
      <address>
      	51 Liverpool Road, Luton
      </address>
    </div>
    <div class="col-xs-9">
   <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2481.824166306601!2d-0.10959818410518234!3d51.53478481652141!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48761b4295221dc9%3A0x8435fd7a0fd47974!2s51+Liverpool+Rd%2C+London!5e0!3m2!1sen!2suk!4v1469434650542" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
	<div class="jumbotron">
		<h1 class="display-3">THE BEST RESTAURANT EVER</h1>
		<p></p>
		<p class="lead">
		<%= link_to "Menu", menu_path, class: "btn btn-lg btn-primary" %>
			<%= link_to "Contact Us", contact_us_path, class: "btn btn-lg" %>
		</p>
	</div></div>

app/views/home/menu.html.erb
<h1>Menu</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Restaurant</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<nav class="navbar navbar-light bg-faded">
			<a class="navbar-brand" href="#">ALL U CAN EAT</a>
			<ul class="nav navbar-nav">
				<li class="nav-item <%= 'active' if current_page?(root_path) %> ">
					<a class="nav-link" href="<%= root_path%>">Home <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item <%= 'active' if current_page?(menu_path) %> ">
					<a class="nav-link" href="<%= menu_path%>">Menu</a>
				</li>
				<li class="nav-item <%= 'active' if current_page?(contact_us_path) %>">
					<a class="nav-link" href="<%= contact_us_path%>">About</a>
				</li>
			</ul>
			<form class="form-inline pull-xs-right">
				<input class="form-control" type="text" placeholder="Search">
				<button class="btn btn-success-outline" type="submit">Search</button>
			</form>
		</nav>
		<%= yield %>
	</div>
	

</body>
</html>